logging:
  fields: "%(asctime)s %(name)s %(funcName)s %(levelname)s %(message)s"
  level: "debug"
  file_out: "app.log"
  unit: "H"
  count: 7
  interval: 24

request:
  domain: "https://qualysapi.qualys.eu"
  path: "/api/2.0/fo"
  headers:
    X-Requested-With: "qualys-fetcher"

endpoints:
  asset:
    endpoint: "/asset/host/"
    options:
      write_to: "assets.json"
      batch_by: "truncation"
    params: 
      static:
        action: "list"
        truncation_limit: 40000
        show_asset_id: 1
        details: "All/AGs"
        show_tags: 1

  asset_group:
    endpoint: "/asset/group/"
    options:
      write_to: "asset_groups.json"
      batch_by: "truncation"
    params: 
      static:
        action: "list"
        truncation_limit: 100
        show_attributes: "ALL"

  knowledgebase:
    endpoint: "/knowledge_base/vuln/"
    options:
      write_to: "knowledgebase.json"
      batch_by: "list"
      list_field: "QID"
      list_param: "qids"
      list_from: [ "detection", "detection_fixed" ]
    params: 
      static:
        action: "list"
        ids: "100027,10005,100067,100076,100089"
        details: "All"

  activity_log:
    endpoint: "/activity_log/"
    options:
      write_to: "activity_log.json"
      batch_by: "truncation"
    params: 
      static:
        action: "list"
        truncation_limit: 4000
      dynamic:
        since_datetime:
          param_type: "timestamp"
          format: "%Y-%m-%dT%H:%M:%SZ"
          subtract:
            hours: 1
          replace:
            minute: 0
            second: 0
            microsecond: 0
        until_datetime:
          param_type: "timestamp"
          format: "%Y-%m-%dT%H:%M:%SZ"
          replace:
            minute: 0
            second: 0
            microsecond: 0

  detection:
    endpoint: "/asset/host/vm/detection/"
    options:
      write_to: "detections.json"
      batch_by: "truncation"
    params: 
      static:
        action: "list"
        #Truncation limit here refers to number of assets, not number of detections
        truncation_limit: 10
        show_asset_id: 1
        show_results: 1
        status: "Active,New,Re-Opened"
        include_ignored: 1
        include_disabled: 1
        arf_service_filter: 0
        arf_config_filter: 0
        arf_kernel_filter: 0
        show_reopened_info: 1
        #show_igs: 1

  detection_fixed: 
    endpoint: "/asset/host/vm/detection/"
    options:
      write_to: "detections_fixed.json"
      batch_by: "truncation"
    params: 
      static:
        action: "list"
        #Truncation limit here refers to number of assets, not number of detections
        truncation_limit: 1000
        show_asset_id: 1
        show_results: 1
        status: "Fixed"
        include_ignored: 1
        include_disabled: 1
        arf_service_filter: 0
        arf_config_filter: 0
        arf_kernel_filter: 0
        show_reopened_info: 1
        show_igs: 1
      dynamic: 
        detection_updated_since:
          param_type: "timestamp"
          format: "%Y-%m-%dT%H:%M:%SZ"
          subtract:
            days: 1
          replace:
            hour: 0
            minute: 0
            second: 0
            microsecond: 0
        last_fixed:
          param_type: "timestamp"
          replace:
            hour: 0
            minute: 0
            second: 0
            microsecond: 0
