logging:
  fields: "%(asctime)s %(name)s %(funcName)s %(levelname)s %(message)s"
  level: "debug"
  file_out: "logs/qualysfetcher.log"
  unit: "H"
  count: 7
  interval: 24

request:
  domain: "https://qualysapi.qualys.eu"
  path: "/api/2.0/fo"
  headers:
    X-Requested-With: "qualys-fetcher"

endpoints:
#  activity_log:
#    endpoint: "/activity_log/"
#    schedule:
#      minute: "1"
#      hour: "*/1"
#    options:
#      write_to: "activity_log.json"
#      item_tag: None
#    params: 
#      static:
#        action: "list"
#        truncation_limit: 5000
#      dynamic:
#        since_datetime:
#          param_type: "timestamp"
#          format: "%Y-%m-%dT%H:%M:%SZ"
#          subtract:
#            hours: 1
#          replace:
#            minute: 0
#            second: 0
#            microsecond: 0
#        until_datetime:
#          param_type: "timestamp"
#          format: "%Y-%m-%dT%H:%M:%SZ"
#          replace:
#            minute: 0
#            second: 0
#            microsecond: 0

  scan:
    endpoint: "/scan/"
    schedule: 
      minute: "5"
      hour: "0"
      day: "*/1"
    options:
      write_to: "scans.json"
      item_tag: "SCAN"
    params: 
      static:
        action: "list"
        show_ags: 1
        show_op: 1
        show_status: 1
      dynamic: 
        launched_after_datetime:
          param_type: "timestamp"
          format: "%Y-%m-%dT%H:%M:%SZ"
          subtract:
            days: 1
          replace:
            hour: 0
            minute: 0
            second: 0
            microsecond: 0
        launched_before_datetime:
          param_type: "timestamp"
          format: "%Y-%m-%dT%H:%M:%SZ"
          replace:
            hour: 0
            minute: 0
            second: 0
            microsecond: 0

  asset:
    endpoint: "/asset/host/"
    schedule:
      minute: "10"
      hour: "0"
      day: "*/1"
    options:
      write_to: "assets.json"
      item_tag: "HOST"
    params: 
      static:
        action: "list"
        truncation_limit: 6000
        show_asset_id: 1
        details: "All/AGs"
        show_tags: 1

  asset_group:
    endpoint: "/asset/group/"
    schedule:
      minute: "30"
      hour: "0"
      day: "*/1"
    options:
      item_tag: "ASSET_GROUP"
      write_to: "asset_groups.json"
    params: 
      static:
        action: "list"
        truncation_limit: 4000
        show_attributes: "ALL"

  detection_fixed: 
    endpoint: "/asset/host/vm/detection/"
    schedule:
      minute: "40"
      hour: "0"
      day: "*/1"
    options:
      write_to: "detections_fixed.json"
      item_tag: "HOST"
    params: 
      static:
        action: "list"
        truncation_limit: 2000 #Truncation limit here refers to number of assets, not number of detections
        show_asset_id: 1
        show_results: 1
        status: "Fixed"
        include_ignored: 1
        include_disabled: 1
        arf_service_filter: 0
        arf_config_filter: 0
        arf_kernel_filter: 0
        show_reopened_info: 1
      dynamic: 
        detection_updated_since:
          param_type: "timestamp"
          format: "%Y-%m-%dT%H:%M:%SZ"
          subtract:
            days: 1
          replace:
            hour: 0
            minute: 0
            second: 0
            microsecond: 0
        detection_updated_before:
          param_type: "timestamp"
          format: "%Y-%m-%dT%H:%M:%SZ"
          replace:
            hour: 0
            minute: 0
            second: 0
            microsecond: 0

  knowledgebase:
    endpoint: "/knowledge_base/vuln/"
    schedule:
      minute: "5"
      hour: "1"
      day: "*/1"
    options:
      write_to: "knowledgebase.json"
      item_tag: "VULN"
    params: 
      static:
        #truncation_limit: #There is no truncation for this API for some reason?
        action: "list"
        details: "All"

  detection:
    endpoint: "/asset/host/vm/detection/"
    schedule:
      minute: "5"
      hour: "2"
      day: "*/1"
    options:
      write_to: "detections.json"
      item_tag: "HOST"
    params: 
      static:
        action: "list"
        truncation_limit: 300 #Truncation limit here refers to number of assets, not number of detections
        show_asset_id: 1
        show_results: 1
        status: "Active,New,Re-Opened"
        include_ignored: 1
        include_disabled: 1
        arf_service_filter: 0
        arf_config_filter: 0
        arf_kernel_filter: 0
        show_reopened_info: 1
        show_igs: 1
