logging:
  fields: "%(asctime)s %(name)s %(funcName)s %(levelname)s %(message)s"
  level: "debug"
  file_out: "logs/qualysfetcher.log"
  unit: "H"
  count: 7
  interval: 24

request:
  domain: "https://qualysapi.qualys.eu"
  path: "/api/2.0/fo"
  headers:
    X-Requested-With: "qualys-fetcher"

endpoints:
  asset:
    endpoint: "/asset/host/"
    schedule:
      minute: "35"
      hour: "0"
      day: "*/1"
    options:
      write_to: "assets.json"
    params: 
      static:
        action: "list"
        truncation_limit: 5000
        show_asset_id: 1
        details: "All/AGs"
        show_tags: 1

  asset_group:
    endpoint: "/asset/group/"
    schedule:
      minute: "30"
      hour: "0"
      day: "*/1"
    options:
      write_to: "asset_groups.json"
    params: 
      static:
        action: "list"
        truncation_limit: 5000
        show_attributes: "ALL"

  knowledgebase:
    endpoint: "/knowledge_base/vuln/"
    schedule:
      minute: "40"
      hour: "0"
      day: "*/1"
    options:
      write_to: "knowledgebase.json"
    params: 
      static:
        action: "list"
        details: "All"

  activity_log:
    endpoint: "/activity_log/"
    schedule:
      minute: "1"
      hour: "*/1"
    options:
      write_to: "activity_log.json"
    params: 
      static:
        action: "list"
        truncation_limit: 5000
      dynamic:
        since_datetime:
          param_type: "timestamp"
          format: "%Y-%m-%dT%H:%M:%SZ"
          subtract:
            hours: 1
          replace:
            minute: 0
            second: 0
            microsecond: 0
        until_datetime:
          param_type: "timestamp"
          format: "%Y-%m-%dT%H:%M:%SZ"
          replace:
            minute: 0
            second: 0
            microsecond: 0

  detection:
    endpoint: "/asset/host/vm/detection/"
    schedule:
      minute: "5"
      hour: "0"
      day: "*/1"
    options:
      write_to: "detections.json"
    params: 
      static:
        action: "list"
        truncation_limit: 1000 #Truncation limit here refers to number of assets, not number of detections
        show_asset_id: 1
        show_results: 1
        status: "Active,New,Re-Opened"
        include_ignored: 1
        include_disabled: 1
        arf_service_filter: 0
        arf_config_filter: 0
        arf_kernel_filter: 0
        show_reopened_info: 1
        #show_igs: 1

  detection_fixed: 
    endpoint: "/asset/host/vm/detection/"
    schedule:
      minute: "1"
      hour: "0"
      day: "*/1"
    options:
      write_to: "detections_fixed.json"
    params: 
      static:
        action: "list"
        truncation_limit: 1000 #Truncation limit here refers to number of assets, not number of detections
        show_asset_id: 1
        show_results: 1
        status: "Fixed"
        include_ignored: 1
        include_disabled: 1
        arf_service_filter: 0
        arf_config_filter: 0
        arf_kernel_filter: 0
        show_reopened_info: 1
        #show_igs: 1
      dynamic: 
        detection_updated_since:
          param_type: "timestamp"
          format: "%Y-%m-%dT%H:%M:%SZ"
          subtract:
            days: 1
          replace:
            hour: 0
            minute: 0
            second: 0
            microsecond: 0
        detection_updated_before:
          param_type: "timestamp"
          format: "%Y-%m-%dT%H:%M:%SZ"
          replace:
            hour: 0
            minute: 0
            second: 0
            microsecond: 0
